[
  "Timestamp",
  "Audit Date",
  "Auditor Name",
  "Warehouse Code",
  "Commodity Health",
  "Commodities available",
  "Upload Photo - Commodity",
  "Infestation / Deterioration Noticed",
  "Infestation / Deterioration Noticed (Remarks)",
  "Upload Photo - Infestation / Deterioration",
  "Fumigation Required",
  "Fumigation Required (Remarks)",
  "Upload Photo -  Fumigation",
  "Dunnage Available",
  "Dunnage Available (Remarks)",
  "Upload Photo - Dunnage Available",
  "Stock kept in countable position",
  "Stock kept in countable position (Remarks)",
  "Upload Photo - Stock kept in countable position",
  "Weighing scale available",
  "Weighing scale available (Remarks)",
  "Upload Photo - Weighing scale",
  "Hygiene / Cleanliness maintained in warehouse",
  "Hygiene / Cleanliness maintained in warehouse (Remarks)",
  "Upload photo - Hygiene / Cleanliness maintained in warehouse",
  "Whether the Bank funded commodities are stored separately and bifurcated",
  "Bank Funded Commodities (Details)",
  "Upload Photo - Bank Funded commodities",
  "Collateral Manager Name",
  "Customer Name",
  "Pledge Board Available",
  "Pledge Board Available - Remarks",
  "Upload Photo - Pledge Board Available",
  "Stack card available",
  "Stack Card Available - Remarks",
  "Upload Photo - Stack card available",
  "Fire equipment available",
  "Fire equipment available - Remarks",
  "Upload Photo - Fire equipment available",
  "Security Guard Available during visit",
  "Security Gaurd Available during visit - Remarks",
  "Upload Photo - Security Guard available during visit",
  "Supervisor available during visit",
  "Supervisor available during visit - Remarks",
  "Upload Photo - Supervisor available during visit",
  "Id card of warehouse personal available",
  "Id card of warehouse personal - Remarks",
  "Upload Photo - Id card of warehouse personal available",
  "Lock and Key in control of CM",
  "Lock and Key - Remarks",
  "Visitors register available",
  "Visitors register available - Remarks",
  "Upload Photo - Visitors register available",
  "Stock register available",
  "Stock register available - Remarks",
  "Upload Photo - Stock register available",
  "Security guard attendance register available",
  "Security guard attendance register available - Remarks",
  "Upload Photo - Security guard's attendance register",
  "Supervisor attendance register available",
  "Supervisor attendance register available - Remarks",
  "Upload Photo - Supervisor's attendance register",
  "Lein register available & Lein marked",
  "Lein register available & Lein marked - Remarks",
  "Upload Photo - Lein register available & Lein marked",
  "Type of warehouse",
  "If Others, please specify the warehouse type",
  "Warehouse stock - Funded stock of - Bank Name",
  "Valid license available",
  "Valid license available - Remarks",
  "Total Warehouse capacity (MT)",
  "Condition of roof",
  "Condition of Roof - Remarks",
  "Upload Photo - Condition of Roof",
  "Plinth Height 3 Feet or More",
  "Plinth Height 3 Feet or More - Remarks",
  "Upload Photo - Plinth Height 3 Feet / More",
  "Number of locks at Gate/Door/Windows",
  "Number of gates / shutters",
  "Ventilation Available",
  "Ventilation Available - Remarks",
  "Upload Photo - Ventilation Available",
  "Condition of warehouse structure",
  "Condition of warehouse structure - Remarks",
  "Upload Photo - Condition of warehouse structure",
  "Leakage inside the warehouse",
  "Leakage inside the warehouse - Remarks",
  "Upload Photo - Leakage inside the Warehouse",
  "Other party details - Name of entity",
  "Remarks - Avg. Bag weight (Kg)",
  "Whether there are any electrical connection inside the warehouse.",
  "If yes, secured or unsecured",
  "Total Quantity available in warehouse as per Bank (MT)",
  "Total Bags available in warehouse as per Bank",
  "Total Quantity available in warehouse as per AgNext (MT)",
  "Total Bags available in warehouse as per AgNext",
  "Quantity Mismatch",
  "Is the Quantity Mismatched in excess or is lesser",
  "Quantity Mismatch Quantity (MT)",
  "Lesser in Quantity is due to",
  "Physical Shortage - No of Bags",
  "Physical Shortage - Quantity (MT)",
  "Physical Shortage - Remarks",
  "DO copy available",
  "DO Copy Available (Remarks)",
  "DO Copy Date",
  "DO Copy Number",
  "Upload photo - DO Copy",
  "WHR Number",
  "WHR Date",
  "WHR Details - No of Bags",
  "WHR Details - Quantity (MT)",
  "WHR Details - Photo",
  "Discrepancy",
  "Inspection Report",
  "Are you sure you want to submit",
  "Reviewed",
  "PDF Status",
  "Document Link",
  "PDF Link",
];
