const MANUAL_DOCS_SOURCE_FOLDER_ID = "1Bl-9W80IzFfx7ZP5prXA7ro2xUaoajeH";

// This function takes a folder which contains docs generated by form publisher and generates the pdfs for them. Just if we have to ever generate pdfs manually for any exceptional case.
async function generatePdfFromTemplate() {
  try {
    const sourceFolder = DriveApp.getFolderById(MANUAL_DOCS_SOURCE_FOLDER_ID);
    const sourceFolderFiles = sourceFolder.getFiles();

    while (sourceFolderFiles.hasNext()) {
      const file = sourceFolderFiles.next();
      console.log("Updating file: " + file.getName());

      updateDocToPdf(file);
    }
  } catch (error) {
    console.log("Error loading template.", error.stack);
    sendErrorEmail(error.stack);
  }
}
