async function objectGenerator(values) {
  const FIELD_DATA_TYPES = {
    BOOLEAN: "boolean",
    STRING: "string",
    NUMBER: "number",
    ARRAY: "array",
    MULTI_TEXT: "multiText",
    MULTI_VALUE: "multiValue",
    DATE: "date",
    FLOAT: "float",
    MULTI_VALUE_RADIO: "multiValueRadio",
  };
  const dbArrOfObject = [
    {
      name: "auditTime",
      title: "Timestamp",
      value: "",
      type: FIELD_DATA_TYPES.DATE,
    },
    {
      name: "auditDate",
      title: "Audit Date",
      value: "",
      type: FIELD_DATA_TYPES.DATE,
    },
    {
      name: "auditorName",
      title: "Auditor Name",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "warehouseCode",
      title: "Warehouse Code",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "commodityHealth",
      title: "Commodity Health",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "availableCommodities",
      title: "Commodities available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "commodityPhotoUrl",
      title: "Upload Photo - Commodity",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "infestationFound",
      title: "Infestation / Deterioration Noticed",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "infestationRemark",
      title: "Infestation / Deterioration Noticed (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "infestationPhotoUrl",
      title: "Upload Photo - Infestation / Deterioration",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "fumigationRequired",
      title: "Fumigation Required",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "fumigationRemarks",
      title: "Fumigation Required (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "fumigationPhotoUrl",
      title: "Upload Photo -  Fumigation",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "dunnageAvailable",
      title: "Dunnage Available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "dunnageRemarks",
      title: "Dunnage Available (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "dunnagePhotoUrl",
      title: "Upload Photo - Dunnage Available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "stockPositionCountable",
      title: "Stock kept in countable position",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "stockPositionRemarks",
      title: "Stock kept in countable position (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "stockPositionPhotoUrl",
      title: "Upload Photo - Stock kept in countable position",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "weighingScaleAvailable",
      title: "Weighing scale available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "weighingScaleRemarks",
      title: "Weighing scale available (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "weighingScalePhotoUrl",
      title: "Upload Photo - Weighing scale",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "warehouseHygieneStatus",
      title: "Hygiene / Cleanliness maintained in warehouse",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "warehouseHygieneRemarks",
      title: "Hygiene / Cleanliness maintained in warehouse (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "warehouseHygienePhotoUrl",
      title: "Upload photo - Hygiene / Cleanliness maintained in warehouse",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "bifurcatedStatus",
      title:
        "Whether the Bank funded commodities are stored separately and bifurcated",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "bifurcatedRemarks",
      title: "Bank Funded Commodities (Details)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "bifurcatedPhotoUrl",
      title: "Upload Photo - Bank Funded commodities",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "collateralManager",
      title: "Collateral Manager Name",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "customerName",
      title: "Customer Name",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "pledgeBoardAvailable",
      title: "Pledge Board Available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "pledgeBoardRemarks",
      title: "Pledge Board Available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "pledgeBoardPhotoUrl",
      title: "Upload Photo - Pledge Board Available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "stackCardAvailable",
      title: "Stack card available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "stackCardRemarks",
      title: "Stack Card Available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "stackCardPhotoUrl",
      title: "Upload Photo - Stack card available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "fireEquipmentAvailable",
      title: "Fire equipment available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "fireEquipmentRemarks",
      title: "Fire equipment available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "fireEquipmentPhotoUrl",
      title: "Upload Photo - Fire equipment available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "securityGuardAvailable",
      title: "Security Guard Available during visit",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "securityGuardRemarks",
      title: "Security Gaurd Available during visit - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "securityGuardPhotoUrl",
      title: "Upload Photo - Security Guard available during visit",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "supervisorAvailableAtVisit",
      title: "Supervisor available during visit",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "supervisorAvailableRemarks",
      title: "Supervisor available during visit - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "supervisorAvailablePhotoUrl",
      title: "Upload Photo - Supervisor available during visit",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "warehousePersonnelIdAvailable",
      title: "Id card of warehouse personal available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "warehousePersonnelIdRemarks",
      title: "Id card of warehouse personal - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "warehousePersonnelIdPhotoUrl",
      title: "Upload Photo - Id card of warehouse personal available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "lockAndKeyControl",
      title: "Lock and Key in control of CM",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "lockAndKeyRemarks",
      title: "Lock and Key - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "visitorsRegisterAvailable",
      title: "Visitors register available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "visitorsAvailableRemarks",
      title: "Visitors register available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "visitorsAvailablePhotoUrl",
      title: "Upload Photo - Visitors register available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "stockRegisterAvailable",
      title: "Stock register available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "stockRegisterRemarks",
      title: "Stock register available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "stockRegisterPhotoUrl",
      title: "Upload Photo - Stock register available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "securityGuardAttendanceRegisterAvailable",
      title: "Security guard attendance register available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "securityGuardAttendanceRegisterRemarks",
      title: "Security guard attendance register available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "securityGuardAttendanceRegisterPhotoUrl",
      title: "Upload Photo - Security guard's attendance register",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "supervisorAttendanceRegisterAvailable",
      title: "Supervisor attendance register available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "supervisorAttendanceRegisterRemarks",
      title: "Supervisor attendance register available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "supervisorAttendanceRegisterPhotoUrl",
      title: "Upload Photo - Supervisor's attendance register",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "leinRegisterAvailable",
      title: "Lein register available & Lein marked",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "leinRegisterRemarks",
      title: "Lein register available & Lein marked - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "leinRegisterPhotoUrl",
      title: "Upload Photo - Lein register available & Lein marked",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "warehouseType",
      title: "Type of warehouse",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "othersWarehouseType",
      title: "If Others, please specify the warehouse type",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "warehouseStock",
      title: "Warehouse stock - Funded stock of - Bank Name",
      value: "",
      type: FIELD_DATA_TYPES.ARRAY,
    },
    {
      name: "licenseAvailable",
      title: "Valid license available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "licenseRemarks",
      title: "Valid license available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "warehouseCapacity",
      title: "Total Warehouse capacity (MT)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "roofCondition",
      title: "Condition of roof",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "roofConditionRemarks",
      title: "Condition of Roof - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "roofConditionPhotoUrl",
      title: "Upload Photo - Condition of Roof",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "plinthHeightStatus",
      title: "Plinth Height 3 Feet or More",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "plinthHeightRemarks",
      title: "Plinth Height 3 Feet or More - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "plinthHeightPhotoUrl",
      title: "Upload Photo - Plinth Height 3 Feet / More",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "noOfLocks",
      title: "Number of locks at Gate/Door/Windows",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "noOfGates",
      title: "Number of gates / shutters",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "ventilationAvailable",
      title: "Ventilation Available",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "ventilationAvailableRemarks",
      title: "Ventilation Available - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "ventilationAvailablePhotoUrl",
      title: "Upload Photo - Ventilation Available",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "warehouseCondition",
      title: "Condition of warehouse structure",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "warehouseConditionRemakrs",
      title: "Condition of warehouse structure - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "warehouseConditionPhotoUrl",
      title: "Upload Photo - Condition of warehouse structure",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "leakageStatus",
      title: "Leakage inside the warehouse",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "leakageRemarks",
      title: "Leakage inside the warehouse - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "leakagePhotoUrl",
      title: "Upload Photo - Leakage inside the Warehouse",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "otherPartyDetails",
      title: "Other party details - Name of entity",
      value: "",
      type: FIELD_DATA_TYPES.ARRAY,
    },
    {
      name: "averageBagWeightRemarks",
      title: "Remarks - Avg. Bag weight (Kg)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "warehouseElectircalConnectionStatus",
      title:
        "Whether there are any electrical connection inside the warehouse.",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "securedWarehouseElectircalConnection",
      title: "If yes, secured or unsecured",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "totalQuantityAvailableInWarehouseAsPerBank",
      title: "Total Quantity available in warehouse as per Bank (MT)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "totalBagsAvailableAsPerBank",
      title: "Total Bags available in warehouse as per Bank",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "totalQuantityAvailableInWarehouseAsPerAgnext",
      title: "Total Quantity available in warehouse as per AgNext (MT)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "totalBagsAvailableAsPerAgnext",
      title: "Total Bags available in warehouse as per AgNext",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "quantityMismatch",
      title: "Quantity Mismatch",
      value: "",
      type: FIELD_DATA_TYPES.BOOLEAN,
    },
    {
      name: "quantityMismatchExcess",
      title: "Is the Quantity Mismatched in excess or is lesser",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_VALUE,
    },
    {
      name: "quantityMismatchQuantity",
      title: "Quantity Mismatch Quantity (MT)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "lesserInQuantityReason",
      title: "Lesser in Quantity is due to",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "physicalShortageBagsCount",
      title: "Physical Shortage - No of Bags",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "physicalShortageQuantity",
      title: "Physical Shortage - Quantity (MT)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "physicalShortageRemarks",
      title: "Physical Shortage - Remarks",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "doCopyAvailable",
      title: "DO copy available",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "doCopyRemarks",
      title: "DO Copy Available (Remarks)",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "doCopyDate",
      title: "DO Copy Date",
      value: "",
      type: FIELD_DATA_TYPES.DATE,
    },
    {
      name: "doCopyNumber",
      title: "DO Copy Number",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "doCopyPhotoUrl",
      title: "Upload photo - DO Copy",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "whrNumber",
      title: "WHR Number",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "whrDate",
      title: "WHR Date",
      value: "",
      type: FIELD_DATA_TYPES.DATE,
    },
    {
      name: "whrDetailsBagsCount",
      title: "WHR Details - No of Bags",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "whrDetailsQuantity",
      title: "WHR Details - Quantity (MT)",
      value: "",
      type: FIELD_DATA_TYPES.NUMBER,
    },
    {
      name: "whrDetailsPhotoUrl",
      title: "WHR Details - Photo",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "discrepancy",
      title: "Discrepancy",
      value: "",
      type: FIELD_DATA_TYPES.MULTI_TEXT,
    },
    {
      name: "inspectionReportProofUrl",
      title: "Inspection Report",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
    {
      name: "inspectionReportUrl",
      title: "PDF Link",
      value: "",
      type: FIELD_DATA_TYPES.STRING,
    },
  ];

  const arrObj = await values.map((val, index) => {
    return { ...dbArrOfObject[index], value: val };
  });
  return arrObj;
}
