const WAREHOUSE_SPREADSHEET_NAME = "Warehouse Sheets"
const WAREHOUSE_SPREADSHEET_ID = "1-ClAJVunzsbSPwrEQXuI-VVrjsKjFFGhBRSN-FJkRK8"
const WAREHOUSE_DETAILS_FOLDER_ID = "1x7NZ9G9WaBq4ntGvkIRrWf1p4mDDWn1p"
const WAREHOUSE_DESTINATION_FILE = "warehouse_details.json";
const WAREHOUSE_CODE_COLUMN_INDEX = 0;
const WAREHOUSE_NAME_COLUMN_INDEX = 1;
const WAREHOUSE_ADDRESS_COLUMN_INDEX = 2;
const WAREHOUSE_LOCATION = 3;
const WAREHOUSE_STATE = 4;
const WAREHOUSE_REGION = 5;
const WAREHOUSE_CM_NAME = 6;

// This function fetches warehouse details from the Google sheet and saves it to a json file in the warehouse details folder.
async function fetchWarehouseDetails() {
  const warehouseSpreadsheet = SpreadsheetApp.openById(WAREHOUSE_SPREADSHEET_ID)

  const dataRange = warehouseSpreadsheet.getDataRange();
  const data = dataRange.getValues();
  const warehouseDetails = {};

  // Traversing the sheets and storing warehouse name and location from it in warehouseDetails object.
   for (let i = 1; i < data.length; i++) { 
    const warehouseCode = data[i][WAREHOUSE_CODE_COLUMN_INDEX];
    const warehouseName = data[i][WAREHOUSE_NAME_COLUMN_INDEX];
    const warehouseAddress = data[i][WAREHOUSE_ADDRESS_COLUMN_INDEX];
    const warehouseLocation = data[i][WAREHOUSE_LOCATION];
    const warehouseState = data[i][WAREHOUSE_STATE];
    const warehouseRegion = data[i][WAREHOUSE_REGION];
    const warehousecmName = data[i][WAREHOUSE_CM_NAME];

    // Storing the details for warehouses uniquely.
    if (!warehouseDetails.hasOwnProperty(warehouseCode)) {
      warehouseDetails[warehouseCode] = {
      name: warehouseName,
      address: warehouseAddress,
      location: warehouseLocation,
      state: warehouseState,
      region: warehouseRegion,
      cmName: warehousecmName
      };
    }
  }

  //Saving warehouseDetails object as json file.
  await saveWarehouseDetailsToFile(warehouseDetails);
}

// This function saves the warehouse details object as a json file in warehouse details folder.
async function saveWarehouseDetailsToFile(warehouseDetails) {
  const folder = DriveApp.getFolderById(WAREHOUSE_DETAILS_FOLDER_ID);
  const jsonData = JSON.stringify(warehouseDetails);

  await deleteFilesIfAlreadyPresent(folder, WAREHOUSE_DESTINATION_FILE);  // Delete any redudant warehouse_details file.
  const file = folder.createFile(WAREHOUSE_DESTINATION_FILE, jsonData, MimeType.PLAIN_TEXT);

  console.log("Warehouse details saved to file:", file.getName());
}

// This function takes the document file and warehouse details objects and sets text for the warehouse name and addresses columns in the document file according to the data stored in the "warehouseDetails" object.
async function updateWarehouseDetails(body, warehouseDetails, code) {
  console.log("warehouse code : " + code);

  // Setting warehouse name and address from warehouseDetails object
  body.replaceText("<<" + WAREHOUSE_NAME + ">>", warehouseDetails[code].name);
  body.replaceText("<<" + WAREHOUSE_ADDRESS + ">>", warehouseDetails[code].address);
}

// This function loads the warehouse details from a json file stored in warehouse details folder where the warehouse sheets is stored (in GDrive).
async function getWarehouseDetails() {
  const folder = DriveApp.getFolderById(WAREHOUSE_DETAILS_FOLDER_ID);

  let files = folder.getFilesByName(WAREHOUSE_DESTINATION_FILE);

  if (!files.hasNext()) {
    await fetchWarehouseDetails(); // In case the warehouse details json file is not present then warehouse data is fetched otherwise file already exists because it will be already there as it is generated by the sheet containing warehouse data
    files = folder.getFilesByName(WAREHOUSE_DESTINATION_FILE);
  }

  const file = files.next();
  const fileContent = file.getBlob().getDataAsString();
  const warehouseDetails = JSON.parse(fileContent); // Storing warehouse_details in an object

  return warehouseDetails;
}